version: '2'
services:
#  web:
#    image:
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    volumes:
#      - go-web-data:/var/lib/go-web-data
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=chitchat
      - POSTGRES_PASSWORD=chitchat
      - POSTGRES_USER=chitchat
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - go-db-data:/var/lib/postgresql/data/pgdata
volumes:
  go-web-data:
  go-db-data: